### ISSUE TITLE
Update e2e pipelines to use a actions/actions-runner-controller runner

### ISSUE THREAD

**Issue by bburky** [naps-dev/testdrive#14]
Update pipeline to use a CI pipeline compatible with actions/actions-runner-controller (ARC) which will provide increased parallelism. Notably this will require the pipeline to install dependencies in the `steps:` or use a `container:` image with all tools included (instead of using anything from the old runner's parent environment).

Ideally all stages in the GitHub Actions workflow specify a `container:`, this is compatible with the ARC `containerMode: kubernetes` and other CI like GitLab which will require an image specified for each CI job.

(I think) GitHub does not persist storage between jobs. The only data the e2e pipeline needs to share between stages is information about the provisioned cluster in MaaS, which can easily be passed as string outputs between jobs. All zarf artifacts can be downloaded and deployed in a single CI job.

GitHub workflow pseudo code:

```yaml
jobs:
  maas:
    container:
      image: mctl
    steps:
      # may need to edit image to have a /bin/bash entrypoint
      - mctl machines release
      - mctl machines deploy-cluster
      - mctl machines get-ip-address
    output: IP_ADDRESS, NODES
  deploy:
    container:
      image: not-build-harness
    steps:
      - zarf install github action (if needed)
      - scp (need to be installed or replace with other tool) download kubeconfig from IP_ADDRESS
      - kubectl cluster-info
      - fetch.sh
      - deploy.sh
  maas-release:
    # optional. This job is only in the PR workflow.
    if: always() # run this stage even if the previous ones fail
    container:
      image: mctl
    steps:
      - mctl machines release NODES
```
